document.writeln("<h5>Useful Highwire Links</h5>");
document.writeln("<ul>");
document.writeln("<li><a href=\"http://highwire.highmark.com/sites/iwov/hwt025/\">Automated Claims Expert</a></li>");
document.writeln("<li><a href=\"http://highwire.highmark.com/sys/isg/object-management/repository/\">Corporate Data Repository</a></li>");
document.writeln("<li><a href=\"http://highwire.highmark.com/isg/mainframe-database-services/\">Database Services</a></li>");
document.writeln("<li><a href=\"http://highwire.highmark.com/sys/ecsmass/documents.html\">Enrollment Communication System (ECS)</a></li>");
document.writeln("<li><a href=\"http://highwire.highmark.com/tc/scorecard/index.jsp?content=content/membership.htm\">Enrollment</a></li>");
document.writeln("<li><a href=\"http://highwire.highmark.com/sites/iwov/hwt022/\">Enrollment Reporting</a> (Access Required)</li>");
document.writeln("<li><a href=\"http://highwire.highmark.com/sites/iwov/hwt021/home.html\">Enrollment Support</a></li>");
document.writeln("<li><a href=\"http://highwire.highmark.com/financial-actuarial/\">Finance Actuarial</a></li>");
document.writeln("<li><a href=\"http://highwire.highmark.com/sites/iwov/hwt115/home.html\">Finance &amp; Actuarial Systems</a></li>");
document.writeln("<li><a href=\"http://highwire.highmark.com/ops/operations/glossary/gl-home.html\">Glossaries &amp; Dictionaries</a></li>");
document.writeln("<li><a href=\"http://highwire.highmark.com/ops/harriet/\">Helpful Answers and Resources for Responding to Inquiries in Extraordinary Time (HARRIET)</a></li>");
document.writeln("<li><a href=\"http://highview.highmark.com/\">HighView</a></li>");
document.writeln("<li><a href=\"http://highwire.highmark.com/sites/sales-marketing-systems/ICISHome.html\">Integrated Customer Information System (ICIS)</a></li>");
document.writeln("<li><a href=\"http://highwire.highmark.com/sites/icis-web-help/\">Integrated Customer Information System (ICIS) Web Help</a></li>");
document.writeln("<li><a href=\"http://highwire.highmark.com/svcadm/signin.do\">Insinq</a> (Access Required)</li>");
document.writeln("<li><a href=\"http://highwire.highmark.com/sites/isg-communications/homepage.html\">Information Services Group (ISG)</a></li>");
document.writeln("<li><a href=\"http://highwire.highmark.com/corp/medical-programs/medical-policy/highmark/home.html\">Medical Policy Bulletins</a></li>");
document.writeln("<li><a href=\"http://highwire.highmark.com/benmntWeb/benefits/BenefitsLogin.do\">Optimum System For Claims Adjudication And Reporting (OSCAR) Benefits</a> (Access Required)</li>");
document.writeln("<li><a href=\"http://highwire.highmark.com/ops/health-services/provider-information-management/\">Provider Information Management</a></li>");
document.writeln("<li><a href=\"https://prc.highmarkblueshield.com/cgi-bin/inetcgi/prc/jsp/Home.do?site=hbs\">Provider Resource Center</a></li>");
document.writeln("<li><a href=\"http://highwire.highmark.com/vk2hfb/pages/search.jsp?context=HIGHWIRE&amp;content=FEEBULLETIN\">Recommended Fee Bulletins</a></li>");
document.writeln("<li><a href=\"http://highwire.highmark.com/sites/iwov/hwt010/\">Technical Assistance Center (TAC)</a></li>");
document.writeln("<li><a href=\"http://highwire.highmark.com/corp/medical-programs/ub-reference-manual/\">Uniform Billing (UB) Reference Manuals</a></li>");
document.writeln("</ul>");
